In [1]:
import numpy as np
Array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(Array)
print(type(Array))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [2]:
len(Array)

3

In [1]:
import numpy as np
# Array of Strings
a=np.array(["Muhammad",'Rizwan','Tanveer','Mobashir'])
print(a)
a.size
# Array of Integers
b=np.array([1,2,3,4,5])
b

['Muhammad' 'Rizwan' 'Tanveer' 'Mobashir']


array([1, 2, 3, 4, 5])

In [3]:
# Vector is a one dimensional array like 
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
len(a)

3

In [8]:
print(a[1])

2


In [10]:
print(a[0:2])

[1 2]


In [11]:
print(a[0:])

[1 2 3]


In [13]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [23]:
#Ones array, all the elements will be just 1, 1,1 etc
c=np.ones(2)
type(c)
c

array([1., 1.])

In [24]:
# empty array
d=np.empty(3)
d

array([0., 0., 0.])

In [29]:
#arange array
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [32]:
# with a specific range of array
f=np.arange(2,20)
len(f)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [2]:
# Continue
g = np.arange(2,20,3)
g

array([ 2,  5,  8, 11, 14, 17])

In [6]:
# Linearly spaced arrays
lsa = np.linspace(0,10, num=5)# we take 5 num between 0 to 10 
lsa

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
# Linearly spaced arrays
lsa = np.linspace(0,12, num=5)# we take 5 num between 0 to 12 
lsa

array([ 0.,  3.,  6.,  9., 12.])

In [13]:
# Specific data types in array
riz=np.ones(5, dtype=np.int8)
riz

array([1, 1, 1, 1, 1], dtype=int8)

In [15]:
# Specific data type in array
riz=np.ones(5, dtype=np.float64)
riz

array([1., 1., 1., 1., 1.])

In [17]:
r=np.ones((3,4))
r

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
r=np.zeros((4,4))
r

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
r=np.empty((2,3))
r

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# 3 Dimensional Array with Ones function
r=np.ones((2,3,4))
r

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
# 3 dimensional Array
r=np.arange(24).reshape(2,3,4)
r

array([], dtype=int32)