# Python with Baba AMmar
## We are learning Data Science with Baba Ammar
### I'm Riz and INSHALLAH I'll be successed in Data Science and be come a pakistani Sciencist

## **My First Code**

In [ ]:
print("Best of Luck Muhammad Rizwan")

## **02_Operators**

In [ ]:
print(2+3)
print(5-2)
print(5*2)
print(5**2)
print(5%2)
print(8/2)
print(8//2)


print(2*3/2**3+4%2)

*solve these kind of equations formula PEMDAS 
Parenthesis Exponents Multiplication Division Abstraction Subtraction* 

## 03_Strings

In [ ]:
print('Muhammad')
print("Rizwan")
print('''Mansha''')
print('''What's Up''')
print("What's up")

## *04_Comments*

In [ ]:
print("How are you brother")


### *Here we are print the strings*

In [ ]:
print("Kesy ho yaar tum")

### *at the start commnet (Ctrl + /)*

## 05_Veriables

In [ ]:
# For Integers
x = 5
print(x)

In [ ]:
y = "My Name Is Rizwan From Pakistan"
print(y)


### x veriable overloaded 

In [ ]:
x = 10
type(float(x))

### *Also Do that*

In [ ]:
x = "My Name is Muhammad Rizwan From Pakistan"
type(x)
x

In [ ]:
y = "Muhammad"," Rizwan"
print(y)



## *Now check the Type of veriables*

In [ ]:
y = "Muhammad Rizwan"
type(y)


# Rules for declearation of Veriables
## 1. Do Not start veriable name with Numbers
## 2. Veriable name should be start from strings, underscore, 
## 3. Veriable name should be discriptive
## 4. Spaces are not allowed between Veriable name
## 5. Do not use keywords function like(start, del, end, test, main, break etc)
## 6. Casesenstive(should use lowercase letters for veriables)

# Indexing in Python

In [ ]:
a = "Samosa Pakora"
a

In [ ]:
a[0]


In [ ]:
a[5]

In [ ]:
a[0:6]

In [ ]:
a[0:13]


# Last index is Exclusive

In [ ]:
len(a)

In [ ]:
a[-6:13]

In [ ]:
a[-1:-6]

In [ ]:
food = "baryani"
food

# Strings Methods

In [ ]:
#Lower all the elements of Strings
food.lower()

In [ ]:
#Upper all the elements of Strings
food.upper()

In [ ]:
#capitalize the first element of the strings
food.capitalize()

In [ ]:
#Replace with one charactor to another
food.replace("b", "Sh")

In [ ]:
#Counting a specific char in all the strings
food.count("a")

### -Find an indexing number in strings

In [ ]:
name = "My name is Muhammad Rizwan, From Lahore Pakistan, I'm a student of BS(Computer Science ) From Virtual University of Pak"
name

In [ ]:
#Find index number of strings
name.find("mm")

### -spilite an string

In [ ]:
name

In [ ]:
name.split(",")

In [ ]:
len(name)

In [ ]:
name.replace("Computer Science", "Software Engineering")

In [ ]:
name.upper()

In [ ]:
name.lower()

In [ ]:
name.capitalize()

In [ ]:
name[80:112]

# Basic Data Structure in Python

### 1- Tuple

### 2- List

### 3- Dictionaries

### 4- Set 

In [ ]:
tup1 = (786, "Riz", 3.1415, True)
tup1

# 1-Indexing of Tuple


In [ ]:
#Access first element in the tuple
tup1[0]

In [ ]:
#In python last number of indexing is exclusive
tup1[0:4] 

In [ ]:
#find the type of tuple
type(tup1) 

In [ ]:
# find the length of the tuple
len(tup1)

In [ ]:
# One more Tupple 
tup2 = (5, "Pakistan", False, 3.5)
tup2

In [ ]:
#Multiplication of Tuple with some integer like 2
tup1*2

### Multiplication of tuple with some integer then the output will be all the element will be multipling with number of multiplication

In [ ]:
# Concatinate two Tupples (Add more than 2 tupples)
tup1 +tup2

# -find the min and max element in the tuple

In [ ]:
tup4 = (5, 10, 15, 20, 25, 30)
tup4

In [ ]:
min(tup4)

In [ ]:
max(tup4)

In [ ]:
tup4 *2

In [ ]:
tup1+tup2+tup4

---

# 2-List
## -Ordered Collection of elements
## -Different kind of elements can be stored
## -You can change the stored elements 
## -All the elements are stored in [ ] paranthises

In [ ]:
list1 = ["Riz", 786, True, 4.5]
list1

In [ ]:
list2 = [3,7,1, 23, 64, 232, 643, 932, 11, 34]
list2

In [ ]:
# Concatinate the two list
list1 + list2

## -> Use the functions of list one by one

In [ ]:
list2

In [ ]:
# Append an element in the list which always linked at the end of the list
list2.append(786)
list2

In [ ]:
#Now find the length of the list
len(list2)

In [ ]:
#Now sort the list elements 
list2.sort()
list2

In [ ]:
#Now Reverse all the elements of list (Desorted)
list2.reverse()
list2

In [ ]:
list1

In [ ]:
(list1 + list2)*2

In [ ]:
#Merge two list in one list
list3 = list1 +list2
list3

In [ ]:
list2.copy()

In [ ]:
list1.copy()

In [ ]:
### -Copy Method in the list 
summer_fruits = ["Manago", "Banana", "Apple", "Tarbooza", "Kharboza"]
spring_fruits = summer_fruits.copy()
spring_fruits



In [ ]:
spring_fruits

In [ ]:
summer_fruits

In [ ]:
len(summer_fruits)

In [ ]:
#Insertion of an elements in the list
spring_fruits.insert(3,"Khurbani")
spring_fruits

In [ ]:
#Clear all the elements in the list to use clear function
summer_fruits.clear()
summer_fruits

In [ ]:
spring_fruits

In [ ]:
spring_fruits.sort()
spring_fruits

In [ ]:
# Count how many elements are in the list so we use count method
spring_fruits.count("Banana")

In [ ]:
summer_fruits

In [ ]:
spring_fruits

In [ ]:
# Concatinate all 2 list of strings
summer_fruits + spring_fruits

In [ ]:
#Merge 2 list of strings in one
merge_fruits = summer_fruits + spring_fruits
merge_fruits

In [ ]:
merge_fruits.sort()
merge_fruits

---

# 3-Dictionaries
### -Unordered collectioin of elements 
### -Mutetable(You can change them)
### -Dictionaries have two things first keys and second values
### -Enclosed with curly brases / { }

In [ ]:
food1 = {"Samosa":30, "Pakora":100, "Raita": 30, "Salad":20}
food1

In [ ]:
#Check the type of food1
type(food1)

In [ ]:
food2 = {"Tiki": 30, "Charkori":50, "Chiken Rolls":50}
food2

In [ ]:
# Concatinate two different Dictionaries
food1.update(food2)
food1

In [ ]:
food1.keys()

In [ ]:
food1.values()

In [ ]:
element = food1.pop('Samosa')
'the value of Samaso is:',element

In [ ]:
food1

In [ ]:
food3 = {"Baryani":786}
food3

In [ ]:
food1.update(food3)
food1

In [ ]:
check=food1.popitem()
check

In [ ]:
food1

In [ ]:
#Setdefault method return the value if the keys are find, if keys are not find in the whole dictionary then the defualt value willbe printed
food1.setdefault("Baryani" ,'Samosa')


In [ ]:
#item() method views all the elements speratedly and second fuction of it change the values of any keys
food1.items()
change_baryani = food1['Baryani'] = 150
change_baryani

In [ ]:
food1.items()

---

# 4- List
- unordered and unidexing
- In listing data structure we use curly brases { }
- Duplicates are not allowed
- Boolein functions are not allowed

In [ ]:
# Example 1
list1 = {"Apple", "Banana", "Cherry"}
list1

In [ ]:
list2 = {"Dates","Mango", "Banana"}
list2

In [ ]:
# Example 2
#Intersection means how many elements of riz1 is same to set2, same elements are intersection of two different sets
riz1 = {1, 2, 3, 4, 5}
riz2 = {1, 0, 8, 9, 1}
riz1.intersection(riz2)

In [ ]:
riz1.difference_update(riz2)
riz1

In [ ]:
# What difference have in the set of riz1 WRT to set riz2
#riz1.difference(riz2)

In [ ]:
riz1.difference_update(riz2)

In [ ]:
# Intersection means find element of which we put the argument in the method of intersection will be finded if it's not find then set(
list1.intersection(list2)

In [ ]:
# add method insert any element which are put the parameter in the add method at the end 
list1.add("Nashpati")
list1

In [ ]:
list1

In [ ]:
#different and intersection are two opposite method difference method are get the element which are not same both the sets
list1.difference(list2)

In [ ]:
#difference_update method means what the difference of list1 have WRT list2, result will show just list1
list2.difference_update(list1)
list2

In [ ]:
list1.add('Biryani')
list1

In [ ]:
list1.add('Dates')
list1

In [ ]:
#Discard & Remove these are two almost same method which are find an element in the set and remove it, but remove raise error and discard not
list1.discard('Birya')
list1

In [ ]:
#isdisjoint function check the two set are disjoint or not means if two sets elements are similar then return Fasle, if not then True
list1.isdisjoint(list2)

# Ploting Start

In [ ]:
#Step-1
import seaborn as sns
import matplotlib.pyplot as plt

#Step-2 set theme
sns.set_theme(style = "ticks",color_codes=True)

#Step-3 load_dataset
kashti = sns.load_dataset("titanic")
print(kashti)


# body mass index (BMS)
# Input Weight
# input Height
# BMI (Ask your self your height)
# Weight
# Calculate the BMI
# Print BMI (My name is ------, and my BMI is ---------)


In [ ]:
Weight = input("What is your Weight ")
Weight = float(Weight)



In [ ]:
Height = input("What is you Height ")
Height = float(Height)



In [ ]:
BMI = Weight/Height**2
BMI

In [ ]:
name = input("what is your name ")


In [ ]:
print("My name is ",name , "& my BMI is ",BMI)

---


# Drow a Barplots with categorical variable using Seaborn and Matplotlib

In [ ]:
#Catplot with Seaborn and matplotlib
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="ticks", color_codes=True)

titanic = sns.load_dataset("titanic")
sns.catplot(x="sex", y="survived", hue = "class", kind = "bar", data = titanic, ci=None) #ci remove for error on bar
plt.show()

In [ ]:
#Countplot
import seaborn as sns
import matplotlib.pyplot as plt
#sns.set_theme(style = "ticks", color_codes=True)
titanic = sns.load_dataset('titanic')
p1 = sns.countplot(x = 'who',data=titanic,hue = 'alone')
p1.set_title("Plot for Counting")
plt.show()


# 01_Line_Plot

#Important Libraries 
Seaborn automatically installs these libraries
- Matplotlib
- Scipy
- Pandas
- Numpy

In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt


# load data_set
phool = sns.load_dataset("iris")
phool

# # Draw a line plot
# sns.lineplot(x ="sepal_length", y= "sepal_width",data = phool)
# # Show Plot
# plt.show()

## Add Title on Lineplot

In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt


# load data_set
phool = sns.load_dataset("iris")


# Draw a line plot
sns.lineplot(x ="sepal_length", y= "sepal_width",data = phool)
# Add Title
plt.title("Lineplot using Iris Data_Set")
# Adjact limits of plot starting
plt.xlim(1.5)
plt.ylim(0.5)
# Show Plot
plt.show()

# Set Style
- dark
- darkgrid
- white
- whitegrid
- ticks

In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt

# load data_set
phool = sns.load_dataset("iris")
plt.figure(figsize=(8,6))

# Draw a line plot
sns.lineplot(x ="sepal_length", y= "sepal_width",data = phool)
# Add Title
plt.title("Lineplot using Iris Data_Set")
sns.set_style("dark")
sns.set_style(style=None,rc=None)
# Show Plot
plt.show()

# Change Figure Size

In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt

# load data_set
phool = sns.load_dataset("iris")


#Change figure size
plt.figure(figsize=(10,8))

# Draw a line plot
sns.lineplot(x ="sepal_length", y= "sepal_width",data = phool)
# Add Title
plt.title("Lineplot using Iris Data_Set")

# Show Plot
plt.show()

In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="dark")

# Simulate data from a bivariate Gaussian
n = 10000
mean = [0, 0]
cov = [(2, .4), (.4, .2)]
rng = np.random.RandomState(0)
x, y = rng.multivariate_normal(mean, cov, n).T

# Draw a combo histogram and scatterplot with density contours
f, ax = plt.subplots(figsize=(6, 6))
sns.scatterplot(x=x, y=y, s=5, color=".15")
sns.histplot(x=x, y=y, bins=50, pthresh=.1, cmap="mako")
sns.kdeplot(x=x, y=y, levels=5, color="w", linewidths=1)

# 02_barplot

In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt


# load data_set
phool = sns.load_dataset("iris")
phool
# # Draw a Barplot
# sns.barplot(x ="species", y= "petal_length",data = phool)
# # Show Plot
# plt.show()

In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt


# load data_set
phool = sns.load_dataset("iris")


# Draw a Barplot
sns.barplot(x ="species", y= "petal_length",data = phool)
# Show Plot
plt.show()

# Grouping

In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt


# load data_set
kashti = sns.load_dataset("titanic")
kashti



In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt


# load data_set
kashti = sns.load_dataset("titanic")


# Draw a Barplot
sns.barplot(x ="who", y= "pclass",hue= "alone",data = kashti)
# Show Plot
plt.show()

# Order Of X axis

In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt


# load data_set
kashti = sns.load_dataset("titanic")


# Draw a Barplot
sns.barplot(x ="who", y= "pclass",hue= "class",data = kashti,order=["child","man","woman"])
# Show Plot
plt.show()

## Remove bar errors
## Change the color of barplot
## Change color palette

In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import mean


# load data_set
kashti = sns.load_dataset("titanic")


# Draw a Barplot
sns.barplot(x ="who", y= "pclass",hue= "alone",data = kashti, order=["child","woman"],color = "red",ci=None,
           palette='pastel',estimator=mean)#ci mean confident intereval
# Show Plot
plt.show()

In [ ]:
# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import mean


# load data_set
kashti = sns.load_dataset("titanic")


# Draw a Barplot
sns.barplot(x ="who", y= "pclass",hue= "alone",data = kashti, order=["child","woman"],color = "red",ci=None,
           palette='pastel',estimator=mean)#ci mean confident intereval
# Show Plot
plt.show()

In [ ]:
#Barplot Horizontally

# Important Libraries
import seaborn as sns
import matplotlib.pyplot as plty


# load data_set
kashti = sns.load_dataset("titanic")


# Draw a Barplot
sns.barplot(x="class", y="fare",data=kashti, 
            linewidth=5, facecolor=(.2,.3,1,1),#facecolor should be between 0 to 1 , 0 means black and 1 mean white
            errcolor="0", edgecolor=".5")

# 03_Boxplot 

In [ ]:
#import seaborn library
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
#draw canvas (baloon board)
sns.set(style="darkgrid")
#load_set_data
kashti = sns.load_dataset('titanic')
#draw boxplot
sns.boxplot(x="class",y='fare',data=kashti,palette='pastel',saturation=1)

In [ ]:

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
#import numpy as py

kashti=sns.load_dataset('iris')
sns.boxplot(x='species',y='petal_length',data=kashti)
kashti.head()

# Showmeans Point 

In [ ]:
sns.boxplot(x='species',y='petal_length',showmeans=True,color='red',saturation=1,data=kashti,
           meanprops={'marker':'*','markersize':'23','markeredgecolor':'Pink'  })
plt.xlabel("Riz",size="20",weight="bold",color="blue")

plt.show()

# Chnage the Symbol of mean point

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as py

kashti=sns.load_dataset('iris')

sns.boxplot(x='species',y='petal_length',showmeans=True,saturation=1,meanprops={'marker':'*','markersize':'23','markeredgecolor':'red'},data=kashti)
#show labels
plt.xlabel("How many species")
plt.ylabel("What is Patel_Length")
plt.title="Iris dataset"
plt.show()

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np

tip=sns.load_dataset('tips')
tip.head()

# Change the color of Hue

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np

tip=sns.load_dataset('tips')
sns.boxplot(x='day',y='tip',data=tip, hue='sex', palette={'Male':'0.5','Female':'0.2'})

# 04_Otherplot

# Lineplot with multifacets

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as py
#Load kiya data set of dots
nuqta = sns.load_dataset('dots')
nuqta


In [ ]:
#color palette selete kiya
palette=sns.color_palette("rocket_r")
    #set_theme of plot
sns.set_theme(style='ticks')
#relplot 
sns.relplot(x='time',y='firing_rate',hue='coherence',col='align',size='choice',
            kind='line',size_order=['T1','T2'],
            palette=palette,height=5,aspect=.85,facet_kws=dict(sharex=False),data=nuqta)

plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as py

sns.set_theme(style='ticks',palette='pastel')
#load data_Set
kashti=sns.load_dataset('titanic')
kashti


In [ ]:
#draw boxplot
sns.boxplot(x='sex',y='fare',hue='alone',
           palette=['m','g'],data=kashti)
#sns.despine(offset=10,trim=True)
plt.xlabel('Plot',size='23',weight='bold')



# Tips Dataset

In [ ]:
import seaborn as sns
sns.set_theme(style='darkgrid',palette='pastel')
t=sns.load_dataset('tips')

sns.boxplot(x='day',y='tip',data=t)
plt.show()


# 05_Intractive Plotly

In [ ]:
import plotly.express as px
df = px.data.gapminder()
df.head()

In [ ]:
import plotly.express as px
df = px.data.gapminder()
fig = px.scatter(df, x="gdpPercap", y="lifeExp", animation_frame="year", 
           size="pop", color="continent", hover_name="country", facet_col="continent",animation_group="country",
           log_x=True, size_max=45, range_x=[100,100000], range_y=[25,90])
fig.show()

In [ ]:
import plotly.express as px

df = px.data.gapminder().query("year == 2007")
df.head()

In [ ]:
import plotly.express as px

df = px.data.gapminder().query("year == 2007")
fig = px.sunburst(df, path=['continent', 'country'], values='pop',
                  color='lifeExp', hover_data=['iso_alpha'])
fig.show()

# 07_3Dimension_plot

In [ ]:
import plotly.express as px
df = px.data.iris()
fig = px.scatter_3d(df, x='sepal_length', y='sepal_width', z='petal_width',
              color='species')
fig.show()

In [ ]:
import plotly.express as px
df = px.data.iris()
fig = px.scatter_3d(df, x='sepal_length', y='sepal_width', z='petal_width',
                    color='petal_length', symbol='species')
fig.show()

# 08_Array with NumPy

In [ ]:
import numpy as np
Array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(Array)
print(type(Array))

In [ ]:
len(Array)

In [ ]:
import numpy as np
# Array of Strings
a=np.array(["Muhammad",'Rizwan','Tanveer','Mobashir'])
print(a)
a.size
# Array of Integers
b=np.array([1,2,3,4,5])
b

In [ ]:
# Vector is a one dimensional array like 
a=np.array([1,2,3])
print(a)

In [ ]:
len(a)

In [ ]:
print(a[1])

In [ ]:
print(a[0:2])

In [ ]:
print(a[0:])

In [ ]:
b=np.zeros(3)
b

In [ ]:
#Ones array, all the elements will be just 1, 1,1 etc
c=np.ones(2)
type(c)
c

In [ ]:
# empty array
d=np.empty(3)
d

In [ ]:
#arange array
e=np.arange(6)
e

In [ ]:
# with a specific range of array
f=np.arange(2,20)
len(f)
f

In [ ]:
# Continue
g = np.arange(2,20,3)
g

In [ ]:
# Linearly spaced arrays
lsa = np.linspace(0,10, num=5)# we take 5 num between 0 to 10 
lsa

In [ ]:
# Linearly spaced arrays
lsa = np.linspace(0,12, num=5)# we take 5 num between 0 to 12 
lsa

In [ ]:
# Specific data types in array
riz=np.ones(5, dtype=np.int8)
riz

In [ ]:
# Specific data type in array
riz=np.ones(5, dtype=np.float64)
riz

In [ ]:
r=np.ones((3,4))
r

In [ ]:
r=np.zeros((4,4))
r

In [ ]:
r=np.empty((2,3))
r

In [ ]:
# 3 Dimensional Array with Ones function
r=np.ones((2,3,4))
r

In [ ]:
import numpy as np
# 3 dimensional Array
r=np.arange(36).reshape(3,3,4)
r

In [ ]:
import numpy as np
np.zeros(5)


In [ ]:
np.ones(5, dtype=int)

In [ ]:
import numpy as np
food = np.empty(5,dtype=int)
food

In [ ]:

np.ones((2,50),dtype=np.int64 )


In [ ]:
np.linspace(0,10,num=5)

In [ ]:
# table of 5
np.arange(5,51,5)

# Array Functions

In [11]:
import numpy as np
a= np.array([24,1,44,6])
a

array([24,  1, 44,  6])

In [12]:
b = np.array([5.4,12.5,65.4,23.6])
b

array([ 5.4, 12.5, 65.4, 23.6])

In [20]:
# Concatenate two arrays
c=np.concatenate((a,b))
c

array([24. ,  1. , 44. ,  6. ,  5.4, 12.5, 65.4, 23.6])

In [25]:
np.sort(c)

array([ 1. ,  5.4,  6. , 12.5, 23.6, 24. , 44. , 65.4])

In [26]:
len(c)

8

In [27]:
np.size(c)

8

In [31]:
# Find max num in the whole Array
np.max(c)



65.4

In [29]:
np.min(c)


1.0

# 2-Dimensional Array

In [38]:
a=np.array([[6,3,1,7],
           [9,2,4,0]])
a

array([[6, 3, 1, 7],
       [9, 2, 4, 0]])

In [56]:
# np.sort(a)

In [54]:
b=np.array([[2,5,1,3],
            [8,3,2,4]])
b

array([[2, 5, 1, 3],
       [8, 3, 2, 4]])

In [55]:
c=np.concatenate((a,b),axis=0)# axis = 0 means down word
c

array([[6, 3, 1, 7],
       [9, 2, 4, 0],
       [2, 5, 1, 3],
       [8, 3, 2, 4]])

In [63]:
c=np.concatenate((a,b),axis=1)# axis = 1 means front side
c

array([[6, 3, 1, 7, 2, 5, 1, 3],
       [9, 2, 4, 0, 8, 3, 2, 4]])

In [61]:
len(c)

4

In [59]:
# size of elements 
np.size(c)

16

In [49]:
np.max(c)

9

In [50]:
np.min(c)

0

In [66]:
a=np.array([[[1,2,3],
           [4,5,6]],
          
          [[7,8,9],
          [0,1,2]],
          
          [[3,4,5],
          [6,7,8]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]],

       [[3, 4, 5],
        [6, 7, 8]]])

In [68]:
# Find how many dimensions of this matrix
a.ndim

3

In [70]:
# for find the shape of array
a.shape

(3, 2, 3)

In [79]:
a=np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [83]:
b=np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [85]:
d= b.reshape(3,2)
d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [81]:
c=np.concatenate((a,b))
c

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6])

In [88]:
b=np.arange(9)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
c=b.reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
d=np.reshape(c,newshape=(1,9),order='C')
d

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [111]:
riz=np.array([0, 1, 2, 3, 4, 5, 6, 7,8])
riz

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
#convert 1-D array into 2-D array
b=riz[np.newaxis, :]
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [120]:
b.shape

(1, 9)

In [123]:
c=np.reshape(b,newshape=(3,3),order='C')
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
c.shape

(3, 3)

In [140]:
c.sum()

36

In [141]:
c.mean()

4.0

In [142]:
d= c.copy()
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [143]:
e=c+d
e

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [147]:
f=np.concatenate((c,d),axis=1)
f

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [ ]:
np.